output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: ""
  # If using Elasticsearch's default certificate
  # ssl.ca_trusted_fingerprint: "<es cert fingerprint>"
setup.kibana:
  host: "kibana:5601"

filebeat.inputs:
  - type: log
    # Change to true to enable this input configuration.
    enabled: true
    # Paths that should be crawled and fetched. Glob based paths.
    paths:
      - /var/log/*.log

